---
title: "class09"
author: "Jelani Lyda"
date: "10/30/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Data input
```{r}
wisc.df <- read.csv("WisconsinCancer.csv")
head(wisc.df)
```

Here we examine data from patient `r nrow(wisc.df)` samples.


```{r}
x <- table(wisc.df$diagnosis)
```
In this data set we have `r x["M"]` cancer and `r x["B"]` non-cancer.

```{r}
#to find a pattern in a string us grep(). To count you can use length(grep()) or
sum(grepl("_mean$", colnames(wisc.df)))
```


```{r}
#convert to a matrix
wisc.data <- as.matrix(wisc.df[,3:32])
diagnosis <- wisc.df$diagnosis
```

```{r}
##check if means are on different scales
#The 2 means coloums, 1 is rows
round(apply(wisc.data, 2, sd), 3)
```

```{r}
wisc.pr <- prcomp(wisc.data, scale = TRUE)
summary(wisc.pr)

```

```{r}
#plot PC1 vs PC2 and color by M/B dignosis
plot(wisc.pr$x, col = diagnosis)
```


```{r}
#create a bi plot of the principle componet analysis
#completly useless, too messy
biplot(wisc.pr)
```


```{r}
pc <- summary(wisc.pr)
pc$importance
```

The first PC captures `r pc$importance[2, "PC1"] * 100`% of the original variance of the dataset.

```{r}
pc$importance[3,] > 0.7
which(pc$importance[3,] > 0.7)[1]
```


```{r}
data.scaled <- scale(wisc.data)
data.dist <- dist(data.scaled)
wisc.hc <- hclust(data.dist)
plot(wisc.hc)
abline(h = 19, col = "red", lty = 2)
```

```{r}
wisc.hc.clusters <- cutree(wisc.hc, k = 2)
table(wisc.hc.clusters, diagnosis)
```


```{r}
#K-means clustering
wisc.km <- kmeans(wisc.data, centers = 2, nstart = 20)
table(wisc.km$cluster, diagnosis)
```


```{r}
wisc.pr.hclust <- hclust(dist(wisc.pr$x[,1:7]), method = "ward.D2")
plot(wisc.pr.hclust)
```

```{r}
grps <- cutree(wisc.pr.hclust, k=2)
table(grps)
table(grps, diagnosis)
plot(wisc.pr$x[,1:2], col=grps)
```

```{r}
#change the grps to a factor so that M is red and B is black
g <- as.factor(grps)
levels(g)
g <- relevel(g,2)
levels(g)
plot(wisc.pr$x[,1:2], col=g)
```

```{r}
library(rgl)
plot3d(wisc.pr$x[,1:3], xlab="PC 1", ylab="PC 2", zlab="PC 3", cex=1.5, size=1, type="s", col=grps)
```
```{r}
wisc.km.pr <- kmeans(wisc.pr$x[, 1:7], centers= 2, nstart= 20)
table(wisc.km.pr$cluster, diagnosis)
table(grps, diagnosis)
```

```{r}
#Predicting data
new <- read.csv("new_samples.csv")
npc <- predict(wisc.pr, newdata = new)
npc
```

```{r}
plot(wisc.pr$x[,1:2], col=g)
points(npc[,1], npc[,2], col="blue", pch=16, cex=3)
text(npc[,1], npc[,2], c(1,2), col="white")
```


















